# Generated by Django 3.2.8 on 2021-10-19 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0004_alter_reservation_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='maxNumberOfSeats',
            new_name='max_number_of_seats',
        ),
        migrations.RenameField(
            model_name='table',
            old_name='minNumberOfSeats',
            new_name='min_number_of_seats',
        ),
    ]
