# Generated by Django 3.2.8 on 2021-10-20 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0005_auto_20211019_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='seat_number',
        ),
    ]
